# Generated by Django 3.1.7 on 2021-05-08 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210508_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='Address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='City',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
