# Generated by Django 3.1.7 on 2021-05-10 06:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainproject', '0002_auto_20210508_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertransaction',
            name='Share_ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainproject.usershare'),
        ),
        migrations.AlterField(
            model_name='usertransaction',
            name='User_ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
