# Generated by Django 3.1.7 on 2021-05-12 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainproject', '0005_auto_20210512_1423'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfollow',
            name='Followerid',
        ),
        migrations.RemoveField(
            model_name='userfollow',
            name='UserID',
        ),
        migrations.RemoveField(
            model_name='usershare',
            name='Share_Owner',
        ),
        migrations.RemoveField(
            model_name='usertransaction',
            name='Share_ID',
        ),
        migrations.RemoveField(
            model_name='usertransaction',
            name='User_ID',
        ),
        migrations.RemoveField(
            model_name='userwallet',
            name='User_ID',
        ),
        migrations.DeleteModel(
            name='UserContent',
        ),
        migrations.DeleteModel(
            name='Userfollow',
        ),
        migrations.DeleteModel(
            name='UserShare',
        ),
        migrations.DeleteModel(
            name='UserTransaction',
        ),
        migrations.DeleteModel(
            name='UserWallet',
        ),
    ]
