# Generated by Django 3.1.7 on 2021-05-13 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_usercontent_userfollow_usershare_usertransaction_userwallet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usershare',
            name='Share_ID',
        ),
    ]
